/**
 * File processing configuration with readonly arrays for immutability
 */
export const fileProcessingConfig = {
  FOLDER_IGNORE_LIST: [
    ".git",
    "bin",
    "build",
    "node_modules",
    ".vscode",
    "dist",
    "output",
  ] as const satisfies readonly string[],
  FILENAME_PREFIX_IGNORE: "test-",
  BINARY_FILE_EXTENSION_IGNORE_LIST: [
    "aac",
    "abw",
    "arc",
    "avif",
    "avi",
    "azw",
    "bin",
    "bmp",
    "bz",
    "bz2",
    "cda",
    "doc",
    "docx",
    "eot",
    "epub",
    "gz",
    "gif",
    "ico",
    "ics",
    "jar",
    "jpeg",
    "jpg",
    "mid",
    "midi",
    "mp3",
    "mp4",
    "mpeg",
    "mpkg",
    "odp",
    "ods",
    "odt",
    "oga",
    "ogv",
    "ogx",
    "opus",
    "otf",
    "png",
    "pdf",
    "ppt",
    "pptx",
    "rar",
    "rtf",
    "svg",
    "tar",
    "tif",
    "tiff",
    "ttf",
    "vsd",
    "wav",
    "weba",
    "webm",
    "webp",
    "woff",
    "woff2",
    "xls",
    "xlsx",
    "xul",
    "zip",
    "3gp",
    "3g2",
    "7z",
    "ear",
    "war",
    "tar",
    "gz",
    "tgz",
  ] as const satisfies readonly string[],
  CODE_FILE_EXTENSIONS: ["js", "ts", "java", "py", "sql"] as const satisfies readonly string[],
  MAX_CONCURRENCY: 50,
} as const;
